from calcule.calcule_ACGT import Calcule_ACGT as ADN
from calcule.repetition import Repetition as rep


#aa="AACTCTATATTTTATTTTTGGAATTTGAGCAGGTTTAGTTGGAACTTCATTAAGTCTTCTAATTCGTACTGAATTAGGTACCCCAGGATCTTTAATTGGAGACGACCAAATTTATAATACTATTGTAACAGCTCATGCATTTATTATAATTTTTTTCATAGTAATACCTATTATAATTGGAGGATTTGGAAATTGATTAGTACCCTTAATATTAGGAGCTCCAGATATAGCATTTCCTCGAATAAATAATATAAGATTTTGATTATTACCCCCATCCTTGACCCTATTAATTTCAAGAAGTATTGTAGAAAATGGTGCTGGTACTGGTTGAACTGTATATCCCCCACTTTCATCTAATATTGCCCACCAAGGAGCTTCTGTTGACTTAGCAATTTTTTCCCTTCATCTTGCAGGTATTTCTTCTATTTTAGGAGCTATTAATTTTATTACAACTATTATTAATATACGAATTAATAATATATCATTTGATCAAATACCATTATTTGTTTGAGCAGTAGGAATTACTGCTTTATTATTATTACTTTCTTTACCAGTTTTAGCTGGTGCTATTACTATATTATTAACAGACCGAAATCTTAATACTTCATTTTTTGATCCTGCTGGAGGAGGTGATCCTATTTTATACCAACATTTATTT"
aa="CCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAA"
#aa="TTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGG"
a=ADN(aa)

a.compter_ACGT()
at, gc=a.compte_AT_et_GC2()
a.affichage_total()
r=rep(aa)
print("-----------------------------------------------------")

print(gc,at)
#r.couper()
#r.affichage_N(15)
#r.nombre_repeter(15)


